# Generated by Django 2.2.24 on 2023-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230303_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Новое здание?'),
        ),
    ]
