# Generated by Django 2.2.24 on 2023-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст жалобы'),
        ),
    ]
