# Generated by Django 2.2.24 on 2023-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(related_name='flats_owners', related_query_name='flats_owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
