# Generated by Django 2.2.24 on 2023-03-04 10:55

from django.db import migrations


def load_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20230304_1313'),
    ]

    operations = [
        migrations.RunPython(load_owners),
    ]
