# Generated by Django 2.2.24 on 2023-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20230304_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(db_index=True, related_name='flats_owners', related_query_name='flats_owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
