# Generated by Django 2.2.24 on 2023-03-06 11:51

from django.db import migrations, models
import phonenumber_field.modelfields


def load_linked_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        flat = Flat.objects.filter(owner=owner.owner)
        owner.flat.set(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0021_auto_20230306_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True,
                                                                 region=None,
                                                                 verbose_name='Нормализованный номер владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер владельца')),

        migrations.RunPython(load_linked_owners)
        ]
