# Generated by Django 2.2.24 on 2023-03-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_auto_20230307_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='fullname',
        ),
    ]
